apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zafira
  name: zafira
  namespace: zebrunner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zafira
  template:
    metadata:
      labels:
        app: zafira
    spec:
      nodeSelector:
        app: zebrunner
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: zafira-config
        image: qaprosoft/zafira:$version
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /zafira-ws/api/status
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /zafira-ws/api/status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
        name: zafira
        ports:
        - containerPort: 8080
          protocol: TCP
